# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: overcoming inertia
email: 
description: > # this means to ignore newlines until "baseurl:"
  trying my best to make it in the world, mostly. trying my best at trying my best the rest of the time.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.andrewventura.com" # the base hostname & protocol for your site
twitter_username: andrewjventura
github_username:  andrewventura
paginate: 5
paginate_path: "/blog/:num"

# Build settings
markdown: kramdown

# Gem dependencies
gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: 