# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Ventura
email: 
description: > # this means to ignore newlines until "baseurl:"
  A Snapchat account that gained self-awareness and access to the physical world, sorta like Hugo Weaving in the first Matrix movie. Tend to write about politics and underground music. Occasionally get funky in a multimedia kinda way.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.andrewventura.com" # the base hostname & protocol for your site
twitter_username: andrewventura
github_username:  andrewventura

# Build settings
markdown: kramdown